# .air.toml - Air configuration for live reload
root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
bin = "./bin/frank"
cmd = "go build -o ./bin/frank ./cmd/frank/main.go"
delay = 1000
exclude_dir = ["assets", "tmp", "vendor", "testdata", "web", "dist", "node_modules", ".git", ".vscode", ".idea"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html", "yaml", "yml", "json"]
include_file = []
kill_delay = "0s"
log = "build-errors.log"
poll = false
poll_interval = 0
rerun = false
rerun_delay = 500
stop_on_root = false
stop_on_change = true
send_interrupt = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true