package: sdk
generate:
  client: true
  models: true
  embedded-spec: true
output: sdk/sdk.gen.go
# Output options
output-options:
  # Skip pruning unused components
  skip-prune: false
  response-type-suffix: "Response"