# Frank Auth SaaS - Development Configuration
# This configuration file is used for local development and testing

# Application Information
app:
  name: "Frank Auth SaaS"
  version: "1.0.0"
  description: "Multi-tenant authentication platform with Clerk.js compatibility"
  environment: "development"
  debug: true
  log_level: "debug"

# Server Configuration
server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s
  shutdown_timeout: 10s
  max_header_bytes: 1048576 # 1MB
  enable_pprof: true # Enable profiling in development
  enable_metrics: true
  metrics_port: 9090

# Database Configuration
database:
  driver: "postgres"
  host: "localhost"
  port: 5432
  name: "frank_auth_dev"
  user: "postgres"
  password: "postgres"
  ssl_mode: "disable"
  timezone: "UTC"
  max_connections: 100
  max_idle_connections: 10
  max_lifetime: "1h"
  log_queries: true # Enable query logging in development
  migration_path: "./migrations"
  auto_migrate: true # Automatically run migrations in development

# Redis Configuration
redis:
  host: "localhost"
  port: 6379
  password: ""
  database: 0
  pool_size: 10
  min_idle_connections: 1
  max_retries: 3
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s
  pool_timeout: 4s
  idle_timeout: 5m
  key_prefix: "frank_auth:"

# Authentication Configuration
auth:
  # JWT Configuration
  jwt_secret: "dev-super-secret-jwt-key-change-in-production"
  jwt_expiry: "24h"
  jwt_refresh_expiry: "7d"
  jwt_issuer: "frank-auth-dev"
  jwt_audience: "frank-auth-users"
  
  # Session Configuration
  session_secret: "dev-session-secret-change-in-production"
  session_expiry: "24h"
  session_cookie_name: "frank_auth_session"
  session_cookie_domain: ""
  session_cookie_secure: false # Set to true in production
  session_cookie_http_only: true
  session_cookie_same_site: "lax"
  
  # Password Policy
  password_policy:
    min_length: 8
    max_length: 100
    require_uppercase: true
    require_lowercase: true
    require_digit: true
    require_special: false
    max_reused_passwords: 3
    prevent_reuse: true
    expiry_days: 90
    strength_check: true
  
  # Account Settings
  require_email_verification: true
  allow_registration: true
  allow_password_reset: true
  max_login_attempts: 5
  lockout_duration: "15m"
  
  # CAPTCHA Configuration (disabled in development)
  enable_captcha: false
  captcha_secret_key: ""
  captcha_site_key: ""

# Multi-Factor Authentication Configuration
mfa:
  totp_issuer: "Frank Auth Dev"
  totp_digits: 6
  totp_period: 30
  totp_skew: 1
  totp_algorithm: "SHA1"
  sms_code_length: 6
  sms_code_expiry: "10m"
  email_code_length: 6
  email_code_expiry: "10m"
  backup_codes_count: 10
  backup_codes_length: 8
  enforce_for_admins: false # Relaxed for development
  default_methods: ["totp", "email"]

# Organization Configuration
organization:
  default_name: "Default Org"
  default_features: ["email", "sms", "magic_link", "oauth"]
  max_members_free: 10
  max_members_paid: 1000
  allow_domain_verification: true
  require_domain_verification: false
  invitation_expiry: "7d"
  
  # Signup Configuration
  signup_fields:
    - name: "email"
      type: "email"
      required: true
      label: "Email Address"
    - name: "first_name"
      type: "text"
      required: true
      label: "First Name"
    - name: "last_name"
      type: "text"
      required: true
      label: "Last Name"
    - name: "company"
      type: "text"
      required: false
      label: "Company"
  
  # Verification Settings
  verification:
    require_email: true
    require_phone: false
    email_verification_expiry: "1h"
    phone_verification_expiry: "5m"

# Security Configuration
security:
  # Rate Limiting
  rate_limit_enabled: true
  rate_limit_per_second: 10
  rate_limit_burst: 20
  rate_limit_cleanup_interval: "1m"
  
  # CORS Configuration
  cors_enabled: true
  cors_allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:3001"
    - "http://localhost:8080"
  cors_allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"]
  cors_allowed_headers:
    - "Authorization"
    - "Content-Type"
    - "X-Requested-With"
    - "X-Organization-Id"
    - "X-User-Type"
    - "X-Publishable-Key"
  cors_exposed_headers: ["X-Total-Count", "X-Page-Count"]
  cors_allow_credentials: true
  cors_max_age: 86400
  
  # Security Headers
  security_headers_enabled: true
  security_headers:
    x_frame_options: "DENY"
    x_content_type_options: "nosniff"
    x_xss_protection: "1; mode=block"
    strict_transport_security: "max-age=31536000; includeSubDomains"
    content_security_policy: "default-src 'self'"
    referrer_policy: "strict-origin-when-cross-origin"
  
  # API Keys
  api_key_length: 32
  api_key_prefix: "fa_dev_"
  api_key_expiry: "1y"

# Email Configuration
email:
  provider: "smtp" # smtp, sendgrid, ses, mailgun
  
  # SMTP Configuration (for development)
  smtp:
    host: "localhost"
    port: 1025 # MailHog for development
    username: ""
    password: ""
    use_tls: false
    use_ssl: false
    skip_verify: true

  # Email Settings
  from_email: "noreply@frankauth.local"
  from_name: "Frank Auth Dev"
  reply_to: "support@frankauth.local"
  
  # Template Settings
  template_path: "./templates/email"
  default_template: "default"
  enable_tracking: false # Disabled in development

# SMS Configuration
sms:
  provider: "console" # console, twilio, aws_sns
  
  # Console Provider (for development - logs to console)
  console:
    enabled: true
  
  # Default Settings
  from_number: "+1234567890"
  default_country_code: "+1"

# OAuth Configuration
oauth:
  # Google OAuth
  google:
    enabled: true
    client_id: "your-google-client-id.apps.googleusercontent.com"
    client_secret: "your-google-client-secret"
    scopes: ["openid", "profile", "email"]
    redirect_url: "http://localhost:8080/v1/oauth/google/callback"
  
  # GitHub OAuth
  github:
    enabled: true
    client_id: "your-github-client-id"
    client_secret: "your-github-client-secret"
    scopes: ["user:email", "read:user"]
    redirect_url: "http://localhost:8080/v1/oauth/github/callback"
  
  # Microsoft OAuth
  microsoft:
    enabled: false
    client_id: ""
    client_secret: ""
    tenant_id: "common"
    scopes: ["openid", "profile", "email"]
    redirect_url: "http://localhost:8080/v1/oauth/microsoft/callback"

# Webhook Configuration
webhooks:
  enabled: true
  max_retries: 3
  retry_delay: "30s"
  timeout: "30s"
  batch_size: 100
  worker_count: 5
  
  # Event Configuration
  events:
    - "user.created"
    - "user.updated"
    - "user.deleted"
    - "session.created"
    - "session.ended"
    - "organization.created"
    - "organization.updated"
    - "membership.created"
    - "membership.updated"

# Audit Configuration
audit:
  enabled: true
  retention_days: 90 # Keep audit logs for 90 days in development
  batch_size: 1000
  flush_interval: "30s"
  
  # Events to Audit
  events:
    authentication: true
    authorization: true
    user_management: true
    organization_management: true
    configuration_changes: true
    security_events: true

# Monitoring Configuration
monitoring:
  # Metrics
  metrics_enabled: true
  metrics_endpoint: "http://localhost:8080/metrics"
  
  # Health Checks
  health_enabled: true
  health_endpoint: "http://localhost:8080/health"
  
  # Tracing (disabled in development to reduce noise)
  tracing_enabled: false
  jaeger_endpoint: "http://localhost:14268/api/traces"
  otlp_endpoint: ""
  sample_rate: 0.1

# Logging Configuration
logging:
  level: "debug"
  format: "console" # console, json
  enable_caller: true
  enable_stacktrace: false
  
  # File Logging (disabled in development)
  file_enabled: false
  file_path: "./logs/frank-auth.log"
  file_max_size: 100 # MB
  file_max_backups: 5
  file_max_age: 30 # days
  file_compress: true

# Templates Configuration
templates:
  path: "./templates"
  email_path: "./templates/email"
  auth_path: "./templates/auth"
  enable_file_watcher: true # Auto-reload templates in development

# Feature Flags (for development experimentation)
features:
  enable_passkeys: true
  enable_magic_links: true
  enable_social_login: true
  enable_enterprise_sso: false # Disabled in development
  enable_advanced_analytics: false
  enable_compliance_mode: false
  enable_multi_region: false

# Development-Specific Settings
development:
  # Enable development tools
  enable_dev_tools: true
  enable_api_docs: true
  enable_swagger_ui: true
  
  # Mock external services
  mock_email_service: true
  mock_sms_service: true
  mock_payment_service: true
  
  # Seed data
  create_seed_users: true
  create_seed_organizations: true
  
  # Performance settings (relaxed for development)
  skip_migrations: false
  disable_auth_for_docs: true