name: Publish NPM Packages

on:
  push:
    tags:
      - "v*"
#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm 9
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"

      - name: Extract version
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Install dependencies in core
        run: cd web && pnpm install --frozen-lockfile

      - name: Build packages
        run: cd web && pnpm build:web

      - name: Build web
        run: cd web && pnpm build

      - name: Update dependencies for publishing
        run: node ./scripts/update-dependencies.js

      - name: Update package version (sdk)
        run: cd web/packages/sdk && pnpm version ${{ steps.extract_version.outputs.VERSION }} --no-git-tag-version


      - name: Publish sdk package
        run: cd web/packages/sdk && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Update package version (react)
        run: cd web/packages/react && pnpm version ${{ steps.extract_version.outputs.VERSION }} --no-git-tag-version

      - name: Publish react package
        run: cd web/packages/react && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
